language: python
sudo: true
python:
  - "3.5"
  - "pypy3"
    # Python3.6 is disabled until https://github.com/tiran/defusedxml/issues/3 lands in travis.
    #  - "3.6"
env:
  global: PYTHONHASHSEED=random
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip --upgrade
  - sudo apt-get install -qq libneon27-dev
  - pip install -r requirements.txt
script:
  - python -m unittest xandikos.tests.test_suite
