language: python
cache: pip
sudo: true
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3.3-5.2-alpha1
env:
  global: PYTHONHASHSEED=random
install:
  - pip install pip --upgrade
  - pip install coverage codecov flake8 pycalendar
  - sudo apt-get install -qq libneon27-dev curl python2.7
  - python setup.py develop
script:
  - make style
  - make coverage
  - mv .coverage .coverage.unit
  - make coverage-litmus
  - mv .coverage .coverage.litmus
  - make coverage-vdirsyncer
  - mv .coverage .coverage.vdirsyncer
  - make coverage-caldavtester
  - mv .coverage .coverage.caldavtester
after_success:
  - codecov --flags unit --file .coverage.unit --required
  - codecov --flags litmus --file .coverage.litmus --required
  - codecov --flags vdirsyncer --file .coverage.vdirsyncer --required
  - codecov --flags caldavtester --file .coverage.caldavtester
